// Code generated by go-bindata.
// sources:
// templates/reveal.html
// DO NOT EDIT!

package presentation

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesRevealHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xac\x52\xcd\x52\xc3\x20\x10\xbe\xfb\x14\x0c\x27\x3d\x08\x77\x25\xb9\xf8\x06\xfa\x04\x04\xb6\x65\x5b\x42\x3a\x2c\x76\xa6\xcd\xf0\xee\x12\x88\x99\x7a\x70\x46\x47\x4f\xf9\xc8\x97\xef\x67\x37\x28\x97\x46\xdf\xdf\x31\xa6\x1c\x68\xbb\x80\x02\x3d\x86\x23\x8b\xe0\x3b\x4e\xe9\xe2\x81\x1c\x40\xe2\xcc\x45\xd8\x75\xdc\xa5\x74\x7a\x92\xd2\xeb\x41\x38\x7d\xc4\x51\x10\xc8\x08\x67\xd0\xfe\xf1\x40\xd2\x10\xad\x27\x51\x20\xff\x17\xbf\xe4\x60\x04\x39\x78\x6d\x8e\xd5\x94\xa1\xed\x78\x7d\xf9\x77\x7f\x8f\x43\xcd\xb8\x42\x18\xde\x63\xd8\x4a\x2b\xd9\xd6\xb1\xc0\x61\xb2\x97\x35\xc8\xe2\x99\x19\xaf\x89\x3a\xde\x3c\xd6\x06\x5f\x29\xf2\x68\x81\x36\x8a\xb1\x79\x8e\x3a\xec\x81\x89\xb7\xca\xe4\xbc\x31\x8a\xc0\x24\x9c\x42\x3f\xcf\x22\x67\x25\x3f\x8f\x37\x52\x08\x76\x13\x28\x59\x62\xd6\x2e\x0d\x36\x4c\x26\xe2\x29\x31\x8a\xe6\x27\x03\x97\xc7\x32\x9d\x18\x31\x88\x43\xe9\x59\x62\xab\xbe\xff\xad\xd9\x61\xfb\xd9\xdf\xda\xf4\xaf\xed\x03\x0c\x98\x50\x7b\xbc\xc2\x7d\x19\xf5\x65\x0a\x3b\xdc\xe7\xfc\xf0\x7c\x2b\x52\xb2\xad\xba\x2c\xbf\x5e\xca\x8f\x00\x00\x00\xff\xff\xc7\x9d\x05\xee\x9c\x02\x00\x00")

func templatesRevealHtmlBytes() ([]byte, error) {
	return bindataRead(
		_templatesRevealHtml,
		"templates/reveal.html",
	)
}

func templatesRevealHtml() (*asset, error) {
	bytes, err := templatesRevealHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/reveal.html", size: 668, mode: os.FileMode(420), modTime: time.Unix(1449691542, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/reveal.html": templatesRevealHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"reveal.html": &bintree{templatesRevealHtml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

